-- MySQL Script generated by MySQL Workbench
-- Sat Jan 22 20:14:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `edicao` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `ano` VARCHAR(4) NOT NULL,
  `resumo` TEXT NULL,
  `miniatura` VARCHAR(255) NULL,
  `categoria_id` INT NOT NULL,
  `editora_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_livros_categorias1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_livros_editoras1_idx` (`editora_id` ASC) VISIBLE,
  CONSTRAINT `fk_livros_categorias1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livros_editoras1`
    FOREIGN KEY (`editora_id`)
    REFERENCES `mydb`.`editoras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`areas_conhecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`areas_conhecimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livros_has_areas_conhecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livros_has_areas_conhecimento` (
  `area_conhecimento_id` INT NOT NULL,
  `livro_id` INT NOT NULL,
  PRIMARY KEY (`area_conhecimento_id`, `livro_id`),
  INDEX `fk_area_conhecimento_has_livros_livros1_idx` (`livro_id` ASC) VISIBLE,
  INDEX `fk_area_conhecimento_has_livros_area_conhecimento1_idx` (`area_conhecimento_id` ASC) VISIBLE,
  CONSTRAINT `fk_area_conhecimento_has_livros_area_conhecimento1`
    FOREIGN KEY (`area_conhecimento_id`)
    REFERENCES `mydb`.`areas_conhecimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_area_conhecimento_has_livros_livros1`
    FOREIGN KEY (`livro_id`)
    REFERENCES `mydb`.`livros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autores_has_livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autores_has_livros` (
  `autor_id` INT NOT NULL,
  `livro_id` INT NOT NULL,
  PRIMARY KEY (`autor_id`, `livro_id`),
  INDEX `fk_autores_has_livros_livros1_idx` (`livro_id` ASC) VISIBLE,
  INDEX `fk_autores_has_livros_autores1_idx` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `fk_autores_has_livros_autores1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `mydb`.`autores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autores_has_livros_livros1`
    FOREIGN KEY (`livro_id`)
    REFERENCES `mydb`.`livros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
